---
- name: Create swap file
  command: dd if=/dev/zero of={{ base_swap_file_path }} bs=1024 count={{ base_swap_file_size_kb }}k
           creates="{{ base_swap_file_path }}"
  tags: swap.file.create

- name: Change swap file permissions
  file: path="{{ base_swap_file_path }}"
        owner=root
        group=root
        mode=0600
  tags: swap.file.permissions

- name: Check swap file type
  command: file {{ base_swap_file_path }}
  register: swapfile
  tags: swap.file.mkswap

- name: Make swap file
  command: "sudo mkswap {{ base_swap_file_path }}"
  when: swapfile.stdout.find('swap file') == -1
  tags: swap.file.mkswap

- name: Write swap entry in fstab
  mount: name=none
         src={{ base_swap_file_path }}
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present
  tags: swap.fstab

- name: Mount swap
  command: "swapon {{ base_swap_file_path }}"
  when: ansible_swaptotal_mb < 1
  tags: swap.file.swapon
